---
#
# Ansible managed
#
repository:
  description: Install and configure mysql on your system.
  homepage: https://robertdebock.nl/
  topics: mysql, mariadb, database, installer, package, ansible, molecule, tox, playbook
