---
- name: Verify
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Ensure ss is available on RedHat
      ansible.builtin.package:
        name: iproute
        state: present
      when:
        - ansible_os_family == "RedHat"

    - name: Check if mysql is bound to 127.0.0.1
      ansible.builtin.command:
        cmd: ss -tulpen
      changed_when: false
      register: mysql_netstat
      failed_when:
        - '"127.0.0.1:3307" not in mysql_netstat.stdout'

    - name: Try root account
      community.mysql.mysql_db:
        name: my_test
        state: present
        login_host: 127.0.0.1
        login_port: 3307
        login_user: root
        login_password: "s3Cur31t4."
        # login_unix_socket: null
        connect_timeout: 30
